apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-scan.fullname" . }}
  labels:
    {{- include "kube-scan.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-scan.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-scan.fullname" . }}
    namespace: {{ .Values.namespace }}
