apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-scan.fullname" . }}
  labels:
    {{- include "kube-scan.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
      - 'rbac.authorization.k8s.io'
      - 'extensions'
      - 'apps'
      - 'batch'
      - 'networking.k8s.io'
    resources:
      - '*'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
