apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-scan.fullname" . }}-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-scan.labels" . | nindent 4 }}
spec:
  ports:
    - name: "{{ .Chart.Name }}-ui"
      port: {{ .Values.environment.port}}
      protocol: TCP
      targetPort: {{ .Values.service.targetport}}
  selector:
    {{- include "kube-scan.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type}}
